config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/:id
  def show
    @post = Post.find(params[:id])
  end

  # POST /posts
  def create

  end

  # GET /posts/new
  def new
  
  end

  # PUT-PATCH /posts/:id
  def update
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<span class="label round"><%= category.name %></span> 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h2><%= link_to "Postit!", root_path %></h2>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul class="left">
        <li><%= link_to 'Add Link', new_post_path %></li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    
    <div id="main" role="main">
      <div class="row">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <div class="post">
    <%= render post.categories %>
    <h2><small><%= link_to post.title, post.url %></small></h2>
    <p><%= post.description %></p>
    <small><span class="subheader">posted by: </span><%= post.creator.username %> at <%= post.created_at %></small>
    <p>
      <small>
        <span><%= link_to "#{post.comments.size} comments", post_path(post) %></span>
      </small>
    </p>
    <hr />
  </div>
<% end %>

app/views/posts/new.html.haml
%h1 Add new post

app/views/posts/new2.html.erb
<h1>Add new post</h1>

<%= form_tag(posts_path, method: "post") do %>
  <%= label_tag(:url, "Url:") %>
  <%= text_field_tag(:url) %>
  <%= label_tag(:description, "Description:") %>
  <%= text_area_tag(:description) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/posts/show.html.erb
<%= render @post.categories %>
<h1><%= link_to @post.title, @post.url %></h1>
<p>
  <%= @post.description %>
</p>

app/views/shared/_content_title.html.erb
<h1><%= title %></h1>